version: '3'
services:
  busybox:
    container_name: busybox
    hostname: mybusybox
    image: busybox:stable-glibc
    command: sleep 3600
  rooter:
    container_name: rooter
    hostname: myrooter
    command: sleep 3600 # Install things like frrouting/frr
    build:
      context: .
      dockerfile: Dockerfile.rooter
      args:
        packages: 'iputils-ping iproute2'
      labels:
        com.example.name: "Rooter"
        com.example.description: "The rooter container image based on debian-11-slim."
        com.example.image: "Debian-11-slim"
