name: Dockefile
on: push
jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hadolint
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: ./p1/Dockerfile.rooter
          ignore: 'DL3008'

