name: Docker-compose
on: push
jobs:
  syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Syntax
        run: docker-compose -f ./p1/docker-compose.yml config
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        uses: isbang/compose-action@v1.4.0
        with:
          compose-file: "./p1/docker-compose.yml"

