name: Publish

on:
  push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish the Badass Rooter Docker image
        run: |
          docker build -f ./p1/Dockerfile.rooter . --tag $image_tag:latest
          docker run $image_tag:latest
          docker push $image_tag:latest
        env:
          image_tag: ghcr.io/ant0wan/bgp-at-doors-of-autonomous-systems-is-simple/rooter


